version: "3.9"

services:

    moki-python:
        image: moki_python
        ports:
            - "8000:80"
        networks:
            - moki_network
    moki_express:
        image: moki_express
        ports:
            - "5000:3000"
        networks:
            - moki_network
    moki_react:
        image: moki_react
        ports:
            - "3000:3000"
        networks:
            - moki_network
networks:
    moki_network:
        driver: bridge        

    

